### ISSUE TITLE
defint_autostepの誤った使用が無警告

### ISSUE THREAD

**Issue by lpha-z** [mskashi/kv#5]
はじめまして（kvにはいつもお世話になっております）、

version 0.4.56（現在の最新版）において、`kv::defint_autostep`の`order`引数に`1`を入れた場合、無警告で精度保証されていない答えが返ってくることを、webデモ使用中に発見しました。
具体的には、以下のコードは`[0,0]`を出力しますが、期待されるものは`0.5`を含む区間です。

```cpp
#include <kv/defint.hpp>

int main() {
    std::cout << kv::defint_autostep( []( auto x ){ return x; }, kv::interval<double>(0), kv::interval<double>(1), 1 )
              << std::endl;
}
```

単に`order`が`1`の場合にエラーを返せばいいようにも思われますが、もしかすると潜在的なバグを示唆しているのかもしれません。
ご検討いただければ幸いです。

**Comment by mskashi** [comment]
確かにこれはバグですね。ありがとうございます。次数が2以上でないと正しく動かないコードになってました　(積分後のorderが1だと積分前のorderが0になり、大事な1次の項が落ちてしまうバグ) 。そもそもdefintのautostepじゃない方との整合性が取れていなかった問題もあり、次のversionではorderを1ずらすようにしたいと考えています。

**Comment by lpha-z** [comment]
c6ec160735acd941c4ac464267c9709b0e5ebe4e（version 0.4.57）で修正されたようなので、閉じておきます。
